import Link from 'next/link';
import { notFound } from 'next/navigation';
import type { Metadata } from 'next';
import { ArrowLeft, ArrowUpRight } from 'lucide-react';
import { projects } from '@/lib/content';
import { TrackedLink } from '@/components/TrackedLink';
import { ProjectFigure } from '@/components/ProjectFigure';
export function generateStaticParams(){return projects.map(p=>({slug:p.slug}));}
export async function generateMetadata({params}:{params:Promise<{slug:string}>}):Promise<Metadata>{const {slug}=await params;const p=projects.find(p=>p.slug===slug);return p?{title:p.name,description:p.summary,alternates:{canonical:'/projects/'+slug},openGraph:{title:p.name+' | Gashahun Demise',description:p.summary,url:'/projects/'+slug}}:{};}
export default async function Project({params}:{params:Promise<{slug:string}>}){const {slug}=await params;const p=projects.find(p=>p.slug===slug);if(!p)notFound();return <main id="main" className="case-study wrap"><Link className="text-link" href="/projects"><ArrowLeft size={16}/>All projects</Link><p className="eyebrow">{p.category}</p><h1>{p.name}</h1><p className="case-intro">{p.summary}</p><div className="tags">{p.tech.map(t=><span key={t}>{t}</span>)}</div><div className="case-banner"><ProjectFigure kind={p.slug}/></div><div className="case-grid"><div><section><h2>The problem</h2><p>{p.problem}</p></section>{p.details.map(([t,d])=><section key={t}><h2>{t}</h2><p>{d}</p></section>)}</div><aside><p className="eyebrow">EVIDENCE & LINKS</p><p className="evidence-note">{p.evidence}</p><TrackedLink event={'repository_'+p.slug} className="button primary" href={p.repo} target="_blank" rel="noopener noreferrer">View repository <ArrowUpRight size={16}/></TrackedLink>{'live' in p&&<a className="button secondary" href={p.live} target="_blank" rel="noopener noreferrer">External demo · unavailable <ArrowUpRight size={16}/></a>}{p.sources.map(([title,url])=><a key={url} className="source" href={url} target="_blank" rel="noopener noreferrer">{title}<ArrowUpRight size={14}/></a>)}</aside></div></main>}
