import Link from 'next/link';
import { ArrowUpRight, Download, ArrowRight } from 'lucide-react';
import { profile, projects } from '@/lib/content';
import { TrackedLink } from '@/components/TrackedLink';
import { ProjectFigure } from '@/components/ProjectFigure';
import { siteUrl } from '@/lib/site';
export const metadata={alternates:{canonical:'/'}};
export default function Home(){return <main id="main">
<script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify({'@context':'https://schema.org','@type':'Person',name:profile.name,url:siteUrl,jobTitle:'Computer Vision Researcher',sameAs:[profile.github,profile.linkedin],alumniOf:{'@type':'CollegeOrUniversity',name:'Addis Ababa Science and Technology University'}})}}/>
<section className="hero wrap"><div className="hero-copy"><p className="eyebrow"><span className="identity-dot"/> COMPUTER VISION · MACHINE LEARNING</p><h1>Gashahun<br/><em>Demise.</em></h1><p className="hero-role">Computer Vision Researcher & Software Engineer</p><p className="intro">I work across computer vision at the Ethiopian Artificial Intelligence Institute—from dataset development to model evaluation—and build the software around it.</p><div className="actions"><Link className="button primary" href="#selected-work">Explore work <ArrowRight size={17}/></Link><TrackedLink event="resume_download" className="button secondary" href={profile.resume} download="Gashahun-Demise-Resume.pdf">Download resume <Download size={16}/></TrackedLink></div><p className="hero-location">Based in Addis Ababa, Ethiopia</p></div><div className="hero-visual"><ProjectFigure/><div className="visual-note"><span>DATA → MODELS → USEFUL SYSTEMS</span><span>Research & engineering</span></div></div></section>
<section className="research-lead wrap" id="selected-work"><div className="section-heading"><p className="eyebrow">01 / FEATURED RESEARCH</p><Link className="text-link" href="/research">Research overview <ArrowUpRight size={16}/></Link></div><div className="research-layout"><div><span className="work-type">COMPUTER VISION / DOCUMENTED PROJECT</span><h2>Understanding disease<br/><em>through leaf images.</em></h2><p>Enset disease classification: image preparation, transfer learning, model comparison, and evaluation beyond a single accuracy score.</p><div className="research-methods"><span>Transfer learning</span><span>Cross-validation</span><span>Grad-CAM</span><span>TensorFlow Lite</span></div><Link className="text-link strong" href="/projects/enset">Read the research study <ArrowUpRight size={20}/></Link></div><div className="method-sheet"><p className="eyebrow">A REPRODUCIBLE RESEARCH WORKFLOW</p>{[['01','Prepare','Labels, preprocessing, and dataset quality.'],['02','Compare','Transfer learning and model fine-tuning.'],['03','Evaluate','Per-class metrics and visual error analysis.'],['04','Optimize','Quantization for TensorFlow Lite.']].map(([n,t,d])=><div className="method-step" key={n}><span>{n}</span><div><h3>{t}</h3><p>{d}</p></div></div>)}<small>Methods documented in the resume. Public training artifacts are not available.</small></div></div></section>
<section className="section wrap"><div className="section-heading"><p className="eyebrow">02 / SELECTED SOFTWARE</p><Link className="text-link" href="/projects">All projects <ArrowUpRight size={16}/></Link></div><div className="work-list">{['hope-lounge','saasforge','taskflow'].map((slug,i)=>{const p=projects.find(p=>p.slug===slug)!;return <Link className="work-row" key={slug} href={'/projects/'+slug}><span className="work-index">0{i+1}</span><div className="work-name"><span className="work-type">{p.category}</span><h3>{p.name}</h3></div><p>{p.summary}</p><ArrowUpRight className="work-arrow" size={26}/></Link>})}</div></section>
<section className="profile-band wrap"><p className="eyebrow">03 / BACKGROUND</p><div><h2>Research grounded<br/>in engineering.</h2><p>B.Sc. in Electrical & Computer Engineering, AASTU. Currently a Computer Vision Researcher at EAII, with experience in image annotation, dataset QA, and model development.</p><div className="inline-links"><Link href="/experience">Experience <ArrowUpRight size={16}/></Link><Link href="/skills">Technical toolkit <ArrowUpRight size={16}/></Link><Link href="/education">Education <ArrowUpRight size={16}/></Link></div></div></section>
</main>}
