import Link from 'next/link';
import { ArrowUpRight, ArrowDown, CodeXml, SquareArrowOutUpRight, Mail, Layers, ScanLine } from 'lucide-react';
import { projects, profile, skills } from '@/lib/content';
import { TrackedLink } from '@/components/TrackedLink';
import { siteUrl } from '@/lib/site';
export const metadata={alternates:{canonical:'/'}};
export default function Home(){return <main id="main">
<script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify({'@context':'https://schema.org','@type':'Person',name:profile.name,url:siteUrl,jobTitle:'Computer Vision Researcher',sameAs:[profile.github,profile.linkedin],alumniOf:{'@type':'CollegeOrUniversity',name:'Addis Ababa Science and Technology University'}})}}/>
<section className="hero"><div className="hero-copy"><p className="eyebrow"><span className="dot"/> COMPUTER VISION · MACHINE LEARNING</p><h1>Turning visual<br/>data into<br/><em>practical AI.</em></h1><p className="intro">I’m Gashahun Demise — a Computer Vision Researcher and Machine Learning Engineer interested in the path from careful experiments to useful systems.</p><div className="actions"><Link className="button primary" href="#work">Explore my work <ArrowDown size={17}/></Link><TrackedLink event="github_click" className="text-link" href={profile.github} target="_blank" rel="noopener noreferrer">View GitHub <ArrowUpRight size={18}/></TrackedLink></div><div className="hero-note"><span>RESEARCH-MINDED</span><span>ENGINEERING-FOCUSED</span></div></div><div className="vision-art" role="img" aria-label="Abstract computer vision illustration showing a leaf within a detection frame; conceptual illustration, not model output"><div className="art-top"><ScanLine size={18}/><span>VISION / FIELD NOTES</span><span>01</span></div><div className="art-grid"><svg viewBox="0 0 400 400" aria-hidden="true"><path className="leaf" d="M197 318C74 279 87 146 264 65C328 210 306 290 197 318Z"/><path className="vein" d="M155 350L263 69M199 244L137 180M218 191L277 164M183 282L249 255M237 138L208 104"/><path className="frame" d="M106 119v-27h27M287 92h27v27M314 279v27h-27M133 306h-27v-27"/><circle cx="211" cy="207" r="5"/><path className="cross" d="M211 180v-15M211 234v15M184 207h-15M238 207h15"/></svg><span className="art-label">INPUT → UNDERSTANDING → APPLICATION</span></div><div className="art-bottom"><span>From pixels to decisions.</span><span>CONCEPTUAL VISUAL</span></div></div></section>
<div className="discipline-strip"><span>Computer vision</span><span>Model evaluation</span><span>Software systems</span><span>Edge AI interests</span></div>
<section id="work" className="section"><div className="section-head"><div><p className="eyebrow">01 / SELECTED WORK</p><h2>Ideas, made tangible.</h2></div><p>Public implementations and an emerging research direction. Each project links back to its evidence.</p></div><div className="projects">{projects.map((project,i)=><article className="project" key={project.slug}><Link className={'project-art art-'+i} href={'/projects/'+project.slug} aria-label={'Read '+project.name+' case study'}>{i===0?<div className="system-diagram"><span>INTERFACE</span><Layers size={38}/><div><span>API</span><span>DATA</span><span>TENANT</span></div></div>:i===1?<div className="kanban-art">{['TO DO','IN PROGRESS','DONE'].map((s,j)=><div key={s}><span>{s}</span>{Array.from({length:3-j},(_,k)=><i key={k}/>)}</div>)}</div>:<div className="research-art"><ScanLine size={74}/><span>ENSET / EDGE AI</span></div>}<span className="art-arrow"><ArrowUpRight size={22}/></span></Link><div className="project-meta"><span>{project.category}</span><span>0{i+1}</span></div><h3><Link href={'/projects/'+project.slug}>{project.name}</Link></h3><p>{project.summary}</p><div className="tags">{project.tech.slice(0,3).map(t=><span key={t}>{t}</span>)}</div><div className="project-links"><TrackedLink event={'project_'+project.slug} href={'/projects/'+project.slug}>Read project notes <ArrowUpRight size={16}/></TrackedLink><span className="status">{project.status}</span></div></article>)}</div></section>
<section id="about" className="section about"><div><p className="eyebrow">02 / ABOUT</p><h2>Research curiosity.<br/>Engineering discipline.</h2><p className="large-copy">I work at the intersection of computer vision, machine learning, and software development.</p><p>I’m an Electrical and Computer Engineering graduate from Addis Ababa Science and Technology University. I work as a Computer Vision Researcher at the Ethiopian Artificial Intelligence Institute.</p><p>My interests include image understanding, thoughtful model evaluation, and the engineering needed to turn experiments into practical applications. I’m interested in research collaboration and AI engineering opportunities.</p><TrackedLink event="linkedin_click" className="text-link" href={profile.linkedin} target="_blank" rel="noopener noreferrer">Connect on LinkedIn <ArrowUpRight size={17}/></TrackedLink></div><div className="skills"><p className="eyebrow">TECHNICAL TOOLKIT</p>{skills.map(([name,items])=><div className="skill-row" key={name}><h3>{name}</h3><p>{items.join(' · ')}</p></div>)}<p className="small">Technologies supported by public project code or my published professional profile.</p></div></section>
<section id="approach" className="section"><div className="section-head"><div><p className="eyebrow">03 / APPROACH</p><h2>Useful systems begin<br/>with better questions.</h2></div><p>The principles I aim to bring to research and engineering work.</p></div><div className="approach-grid">{[['01','Understand the data','Start with provenance, label quality, class balance, and a split strategy that avoids leakage.'],['02','Evaluate beyond a score','Look at per-class behavior, failure cases, and the limits of what an experiment can establish.'],['03','Design for the real world','Consider latency, resource constraints, clear interfaces, and maintainable software from the outset.']].map(([n,t,d])=><article key={n}><span className="number">{n}</span><h3>{t}</h3><p>{d}</p></article>)}</div></section>
<section className="section background"><p className="eyebrow">04 / BACKGROUND</p><h2>A foundation in engineering.</h2><div className="timeline"><article><span>PROFESSIONAL PROFILE</span><div><h3>Computer Vision Researcher</h3><p>Ethiopian Artificial Intelligence Institute</p></div></article><article><span>2025 · EDUCATION</span><div><h3>B.Sc. Electrical & Computer Engineering</h3><p>Addis Ababa Science and Technology University</p></div></article></div></section>
<section id="contact" className="section contact"><p className="eyebrow">05 / LET’S CONNECT</p><h2>Have a meaningful<br/>problem to work on?</h2><p>For research collaborations, AI engineering opportunities, or a conversation about my work.</p><TrackedLink event="email_click" className="email-link" href={'mailto:'+profile.email}>{profile.email} <ArrowUpRight/></TrackedLink><div className="contact-links"><TrackedLink event="github_click" href={profile.github} target="_blank" rel="noopener noreferrer"><CodeXml size={19}/>GitHub</TrackedLink><TrackedLink event="linkedin_click" href={profile.linkedin} target="_blank" rel="noopener noreferrer"><SquareArrowOutUpRight size={19}/>LinkedIn</TrackedLink><a href={'mailto:'+profile.email}><Mail size={19}/>Email</a></div></section>
</main>}
