import Link from 'next/link';
import { ArrowUpRight, Download, MapPin, Mail, SquareArrowOutUpRight, ScanLine, CodeXml, Layers } from 'lucide-react';
import { profile } from '@/lib/content';
import { TrackedLink } from '@/components/TrackedLink';
import { siteUrl } from '@/lib/site';
export const metadata={alternates:{canonical:'/'}};
const strengths=[['COMPUTER VISION','Agricultural image understanding and careful model evaluation',ScanLine],['PRACTICAL AI','Dataset quality, TensorFlow Lite, and deployment constraints',Layers],['FULL STACK','Python APIs and React interfaces for usable software',CodeXml]] as const;
export default function Home(){return <main id="main">
<script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify({'@context':'https://schema.org','@type':'Person',name:profile.name,url:siteUrl,jobTitle:'Computer Vision Researcher',sameAs:[profile.github,profile.linkedin],alumniOf:{'@type':'CollegeOrUniversity',name:'Addis Ababa Science and Technology University'}})}}/>
<section className="hero"><div className="hero-copy"><p className="eyebrow">COMPUTER VISION & SOFTWARE ENGINEERING</p><h1>Gashahun Demise<span>From image data to practical AI.</span></h1><p className="intro">Computer Vision Researcher at EAII, focused on dataset quality, thoughtful evaluation, and the software that makes AI useful.</p><div className="strengths">{strengths.map(([label,text,Icon])=><article key={label}><Icon size={20}/><h3>{label}</h3><p>{text}</p></article>)}</div><div className="actions"><TrackedLink event="email_click" className="button primary" href={'mailto:'+profile.email}>Contact me <ArrowUpRight size={17}/></TrackedLink><Link className="button secondary" href="/projects">View projects <ArrowUpRight size={17}/></Link><TrackedLink event="resume_download" className="button secondary" href={profile.resume} download="Gashahun-Demise-Resume.pdf">Download resume <Download size={17}/></TrackedLink></div><div className="social-links"><a href={profile.github} target="_blank" rel="noopener noreferrer"><CodeXml size={17}/>GitHub</a><a href={profile.linkedin} target="_blank" rel="noopener noreferrer"><SquareArrowOutUpRight size={17}/>LinkedIn</a></div></div><aside className="contact-card" aria-label="Contact information"><div><span className="eyebrow"><MapPin size={16}/>LOCATION</span><p>Addis Ababa, Ethiopia</p></div><div><span className="eyebrow"><Mail size={16}/>EMAIL</span><a href={'mailto:'+profile.email}>{profile.email}</a></div><div><span className="eyebrow"><ScanLine size={16}/>CURRENT ROLE</span><p>Computer Vision Researcher<br/><small>Ethiopian Artificial Intelligence Institute</small></p></div><div><span className="eyebrow"><SquareArrowOutUpRight size={16}/>LINKEDIN</span><a href={profile.linkedin} target="_blank" rel="noopener noreferrer">in/gashahun-demise <ArrowUpRight size={14}/></a></div></aside></section>
<section className="section overview-about"><p className="eyebrow">A LITTLE ABOUT ME</p><h2>Research curiosity.<br/>Engineering discipline.</h2><p className="large-copy">I work at the intersection of computer vision, machine learning, and software development.</p><p>I’m an Electrical and Computer Engineering graduate from Addis Ababa Science and Technology University. My research interests include agricultural image understanding, annotation pipelines, and practical model deployment. I also build APIs and web applications that connect technical systems with usable interfaces.</p><div className="overview-grid">{strengths.map(([label,text,Icon])=><article className="panel" key={label}><Icon className="card-icon"/><h3>{label}</h3><p>{text}</p></article>)}</div></section>
<section className="section collaboration-section"><p className="eyebrow">BUILT TOGETHER</p><h2>Collaboration, put into practice.</h2><p>Selected projects developed with <strong>Gosaye Woyo</strong>, connecting real needs with practical software.</p><div className="card-grid"><article className="panel"><p className="eyebrow">HOPE LOUNGE · LIVE APPLICATION</p><h3>Hope Lounge QR Menu</h3><p>A multilingual menu and restaurant workspace for guests and staff.</p><Link className="button secondary" href="/projects/hope-lounge">Explore project <ArrowUpRight size={16}/></Link></article><article className="panel"><p className="eyebrow">STUDENT & INDUSTRY COORDINATION</p><h3>Internship Hub</h3><p>A shared workspace for placements, work reports, and supervisor feedback.</p><Link className="button secondary" href="/projects/internship-hub">Explore project <ArrowUpRight size={16}/></Link></article></div></section>
</main>}
