export const profile = {
 name: 'Gashahun Demise', github: 'https://github.com/gashahundemise21', linkedin: 'https://www.linkedin.com/in/gashahun-demise/', email: 'gashahundemise21@gmail.com', resume: '/resume/gashahun-demise-resume.pdf',
};
export const projects = [
 {slug:'saasforge',name:'SaaSForge',category:'Full-stack engineering',status:'Public implementation',summary:'A multi-tenant foundation for B2B software, with a Python API and a Next.js interface.',problem:'Business applications need a consistent way to separate organizations, authenticate users, and manage shared workflows.',scope:'The public repository includes frontend and backend application code, database migrations, API services, and test suites. Individual contribution history has not been independently established.',tech:['Python','FastAPI','Next.js','PostgreSQL','SQLAlchemy','Docker'],repo:'https://github.com/gashahundemise21/saasforge',details:[["Implementation", "Next.js frontend, FastAPI backend, PostgreSQL storage, and database migrations."], ["Organization access", "Authentication resolves organization membership for shared application workflows."], ["Status", "Public source includes API and tenant-boundary tests. A production deployment and security audit are not documented."]],sources:[['Architecture','https://github.com/gashahundemise21/saasforge/blob/HEAD/docs/architecture.md'],['Authentication dependencies','https://github.com/gashahundemise21/saasforge/blob/HEAD/backend/app/api/deps.py'],['API test suite','https://github.com/gashahundemise21/saasforge/tree/HEAD/backend/tests/api/v1']]},
 {slug:'taskflow',name:'TaskFlow',category:'Interface engineering',status:'Public implementation',summary:'A focused Kanban interface that organizes tasks into To Do, In Progress, and Done.',problem:'A task board needs a clear workflow and predictable controls for everyday task management.',scope:'The repository contains React components for the board, task cards, search, status selection, task editing, and confirmation dialogs, alongside component tests.',tech:['React','TypeScript','Vite','Vitest'],repo:'https://github.com/gashahundemise21/task-board-app',details:[["Features", "Three task columns, editing, search, status filters, and deletion confirmations."], ["Implementation", "React and TypeScript components, built with Vite. Component tests use Vitest."], ["Status", "Public source is available. No hosted demo is linked."]],sources:[['Board component','https://github.com/gashahundemise21/task-board-app/blob/HEAD/src/components/Board.tsx'],['Components and tests','https://github.com/gashahundemise21/task-board-app/tree/HEAD/src/components'],['Package configuration','https://github.com/gashahundemise21/task-board-app/blob/HEAD/package.json']]},
 {"slug": "internship-hub", "name": "Internship Hub", "category": "Collaborative project · Django", "status": "Maintained implementation", "summary": "A student internship workspace for placements, daily reports, advisor feedback, and company coordination.", "problem": "Students, academic advisors, and industry supervisors need a shared view of placements and progress.", "scope": "A collaborative project credited to Gashahun Demise and Gosaye Woyo. This maintained edition builds on the original gashahun21 repository, preserving author metadata and source attribution.", "tech": ["Python", "Django", "Django Channels", "SQLite", "MySQL", "HTML/CSS"], "repo": "https://github.com/gashahun21/Internship-Management-System", "details":[["Collaboration", "Developed with Gosaye Woyo, based on the original gashahun21 repository."], ["Features", "Role-specific workspaces for students, advisors, supervisors, and company administrators."], ["Maintenance", "The local maintained edition improves sign-in, configuration, and approval checks. AI recommendations remain planned; legacy permissions need further review."]], "sources": [["Original project", "https://github.com/gashahun21/Internship-Management-System"], ["Original README", "https://github.com/gashahun21/Internship-Management-System/blob/main/README.md"], ["Application workflow", "https://github.com/gashahun21/Internship-Management-System/blob/main/myproject/myapp/views.py"]]},
 {"slug": "hope-lounge", "name": "Hope Lounge QR Menu", "category": "Collaborative project · Restaurant software", "status": "Live application", "summary": "A QR menu and restaurant workspace developed for Hope Lounge with Gosaye Woyo.", "problem": "Guests need a convenient mobile menu, while staff need tools to keep items and categories up to date.", "scope": "Developed by Gashahun Demise and Gosaye Woyo for Hope Lounge, as confirmed by the project owner. The live application links to hopeloungemenu.com; the maintained repository preserves the original Gosa5497 source credit.", "tech": ["React", "Django REST Framework", "Vite", "i18next", "Cloudinary"], "repo": "https://github.com/Gosa5497/qr_menu", "live": "https://hopeloungemenu.com/", "details":[["Collaboration", "Developed with Gosaye Woyo for Hope Lounge. Original source is credited to Gosa5497."], ["Features", "Guests can browse the menu in English, Amharic, and Oromo. Staff tools manage items, categories, and QR codes."], ["Implementation", "React and Vite frontend with a Django REST API. The live application is available at hopeloungemenu.com."]], "sources": [["Live Hope Lounge application", "https://hopeloungemenu.com/"], ["Original collaborative source", "https://github.com/Gosa5497/qr_menu"], ["Original README", "https://github.com/Gosa5497/qr_menu/blob/main/README.md"]]},
 {slug:'enset',name:'Enset Disease Guard',category:'Computer vision · research direction',status:'Repository scaffold',summary:'A research direction toward enset disease classification and practical edge AI.',problem:'The proposed focus is image-based support for recognizing enset disease, with attention to agricultural use and deployment constraints.',scope:'The public Enset-Disease-Guard-EdgeAI repository currently contains a title-only README. This page describes the research direction; it does not claim a completed classifier.',tech:['Computer vision','Image classification','Edge AI'],repo:'https://github.com/gashahundemise21/Enset-Disease-Guard-EdgeAI',details:[["Research focus", "Image-based enset disease classification and deployment on constrained devices."], ["Current status", "The public repository contains a title-only README. Dataset, training code, model, and evaluation results are not published."]],sources:[['Public README','https://github.com/gashahundemise21/Enset-Disease-Guard-EdgeAI/blob/HEAD/README.md']]},
] as const;
export const skills = [
 ['AI & image processing',['Computer vision','TensorFlow','scikit-learn','OpenCV']],
 ['Python & data',['Python','NumPy','Pandas','SQL']],
 ['Applications & APIs',['React','TypeScript','Next.js','FastAPI','Django']],
 ['Engineering tools',['Git','GitHub','PostgreSQL','Docker']],
] as const;
